title: ZACHARY FETTERS
baseurl: "/"
url: "https://zachfetters.design"
post_dirs: true
permalink: pretty

theme: null
plugins:
  - jekyll-feed

kramdown:
  input: GFM

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true