title: ZACHARY FETTERS
email: zachfett@protonmail.com
description: 
baseurl: ""
post_dirs: true
permalink: /:categories/:title/

theme: null
plugins:
  - jekyll-feed

kramdown:
  input: GFM

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true