title: ZACHARY FETTERS
baseurl: ""
url: "https://zachfetters.design"
post_dirs: true
include: [_pages]
permalink: pretty

theme: null
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true