[[plugins]]
  package = "netlify-plugin-minify-html"
  [plugins.inputs]
    contexts = [
      'production',
      'branch-deploy',
      'deploy-preview'
    ]

  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseInlineTagWhitespace = false